### PR TITLE
Updated GEOS GNSSRO configuration.

### PR DESCRIPTION
**Pull request by gmao-jjin3**
## Description

Updated GNSSRO configuration after its GEOS GSI operator is added in UFO. UFO results are almost identical to GEOS results.   

## Dependencies

- [ ] waiting on https://github.com/JCSDA-internal/ufo/pull/3062

### CODE REVIEW

**Comment by gmao-jjin3** [comment]
UFO and GSI results match completely for data at 00h 06/15/2022, but not so perfectly for data at 00h 12/12/2021.  
```
/discover/nobackup/jjin3/jedi/JediUfoTests_iodav3/Output.gps_jcsda/gps_bend_qc_2022061500.nc4
total number of data = 763758
=====================================================
Pass QC in GSI, but not in JEDI
number of obs 0
=====================================================
Pass QC in JEDI, but not in GSI
number of obs 0
*******************************************************************
Pass QC in JEDI, err_diff |(JEDI_err - GI_err)/GSI_err| > 0.1
number of obs 0

```
```
/discover/nobackup/jjin3/jedi/JediUfoTests_iodav3/Output.x0048.jj_20230818/gps_bend_qc_2021121200.nc4
total number of data = 635363
=====================================================
Pass QC in GSI, but not in JEDI
1 ----- lat= 40.77443  lon= 276.47977
1  h= 37458.7  sat= 42  class= 401  gsihofx= 9.508066e-05  jedihofx= 9.508419e-05  gsiQC= 0  JediQC= 19 
  gsi:(o-f)/o= -0.036753464  jedi:(o-f)/o= -0.03679202  
1  gsier0= 6.7459456e-07  jedier0= 6.746067e-07  gsierr= 1.5084393e-06  jedierr= -3.3687953e+38  

number of obs 1
=====================================================
Pass QC in JEDI, but not in GSI
number of obs 0
*******************************************************************
Pass QC in JEDI, err_diff |(JEDI_err - GI_err)/GSI_err| > 0.1
1 ----- lat= 18.61896  lon= 341.6662 err_diff= 0.41421357
1  h= 2121.0  sat= 751  class= 402  gsihofx= 0.017271817  jedihofx= 0.01727187  gsiQC= 0  JediQC= 0  
1  gsier0= 0.0018117939  jedier0= 0.001811794  gsierr= 0.0018117939  jedierr= 0.0025622635  

2 ----- lat= 18.61733  lon= 341.68826 err_diff= 0.41421363
2  h= 2238.5  sat= 751  class= 402  gsihofx= 0.01704248  jedihofx= 0.017042462  gsiQC= 0  JediQC= 0  
2  gsier0= 0.0018345745  jedier0= 0.0018345746  gsierr= 0.0018345745  jedierr= 0.0025944803  

3 ----- lat= 40.78244  lon= 276.48596 err_diff= -0.105555475
3  h= 36230.2  sat= 42  class= 401  gsihofx= 0.00011850889  jedihofx= 0.0001185131  gsiQC= 0  JediQC= 0  
3  gsier0= 7.584242e-07  jedier0= 7.584389e-07  gsierr= 1.695888e-06  jedierr= 1.5168778e-06  

4 ----- lat= 40.78024  lon= 276.48444 err_diff= -0.10559052
4  h= 36537.8  sat= 42  class= 401  gsihofx= 0.00011223361  jedihofx= 0.00011222968  gsiQC= 0  JediQC= 0  
4  gsier0= 7.359602e-07  jedier0= 7.359456e-07  gsierr= 1.645657e-06  jedierr= 1.4718912e-06  

5 ----- lat= 40.7782  lon= 276.48288 err_diff= -0.10557314
5  h= 36844.0  sat= 42  class= 401  gsihofx= 0.00010626162  jedihofx= 0.000106261614  gsiQC= 0  JediQC= 0  
5  gsier0= 7.146095e-07  jedier0= 7.146092e-07  gsierr= 1.5979153e-06  jedierr= 1.4292184e-06  

6 ----- lat= 40.77641  lon= 276.4814 err_diff= -0.105564795
6  h= 37151.1  sat= 42  class= 401  gsihofx= 0.00010054063  jedihofx= 0.00010054242  gsiQC= 0  JediQC= 0  
6  gsier0= 6.94159e-07  jedier0= 6.9416524e-07  gsierr= 1.5521867e-06  jedierr= 1.3883305e-06  

number of obs 6
```

**Comment by danholdaway** [comment]
Is er0 vs err the initial and final error?

**Comment by gmao-jjin3** [comment]
> Is er0 vs err the initial and final error?

The er0 is the assigned initial error and err is the final error.

**Comment by danholdaway** [comment]
Surprising that it could work perfectly one day and not another day. Perhaps our putting our faith in analyzing a single cycle for all the instruments was not a good idea!

**Review by danholdaway — APPROVED** [review]

**Comment by gmao-jjin3** [comment]
> Surprising that it could work perfectly one day and not another day. Perhaps our putting our faith in analyzing a single cycle for all the instruments was not a good idea!

I think the other way. We know it's not going to be perfect all the time, but we have faith in we added.

**Pull request merged**
