### PR TITLE
Add Surface Ship YAML for ufo_testing

### PR DESCRIPTION
**Pull request by asewnath**
## Description

Adding the sfcship yaml file that was validated on x48 data. Note that jianjun new files with the pressure changes were used to get GSI and UFO to agree. 

## Dependencies

- [ ] waiting on JCSDA-internal/ufo/pull/2999

### CODE REVIEW

**Review by gmao-jjin3 — APPROVED** [review]
Well done.

**Comment by danholdaway** [comment]
When I run this I get the error: `Error: Variable surface_altitude not found in .../sfcship_geovals.20211211T210000Z.nc4`

**Comment by asewnath** [comment]
> When I run this I get the error: `Error: Variable surface_altitude not found in .../sfcship_geovals.20211211T210000Z.nc4`

The field `geovar_sfc_geomz: surface_geometric_height` was accidentally deleted for airTemperature and virtualTemperature. It should be corrected now

**Comment by danholdaway** [comment]
Thanks @asewnath I triggered the tests https://github.com/GEOS-ESM/swell/actions/runs/6099912328. If they pass we can merge.

**Comment by asewnath** [comment]
frequency of datetime vs. datetime

Screenshot 2023-09-07 at 4 18 18 PM

**Comment by danholdaway** [comment]
Superseded by https://github.com/GEOS-ESM/swell/pull/226

**Pull request closed without merging**
