### PR TITLE
MW: Revised coeffs scalling emissivity term in surf Jacobian

### PR DESCRIPTION
**Pull request by rtodling**
## Description

Though much less that for IR, the emissivity terms for the surface Jacobian for AMSUA and ATMS also seem to benefit from a revision -  all, expect mixed surfaces are multiplied by a factor of 5.

here is an illustration of 2 JEDI swell configurations (default; top)) and the one proposed here (bot) compared agains GSI - the figs are for Tskin increment differences w/ GSI.

 
ts-dueAllMW-diff-gsiX2jedi

## Dependencies

None

## Impact

None

### CODE REVIEW

**Comment by gmao-wgu** [comment]
Are the large differences in the Ts and emissivity sensitivity between GSI and JEDI due to background interpolation differences(GeoVals) or potential bugs in the CRTM interface in JEDI?

**Comment by gmao-yzhu** [comment]
We are not using surface-sensitive AMSU-A and ATMS radiances. I'm not sure why Ts increment is sensitive to their emissivity jacobians? I probably missed something here? 

@gmao-yzhu You are missing that I am matching what GSI is doing ... so whatever question is this respect must be answered in the GSI sense.

**Comment by mjkagnes123** [comment]
> We are not using surface-sensitive AMSU-A and ATMS radiances. I'm not sure why Ts increment is sensitive to their emissivity jacobians? I probably missed something here?
> 
> @gmao-yzhu You are missing that I am matching what GSI is doing ... so whatever question is this respect must be answered in the GSI sense.

Observations of some AMSUA channels (4 and 5)  and ATMS oxygen channels ( 5, 6, 17, 18), located at the outer edges of the absorption band, do have  sensitivity to surface. 
Picture1

**Comment by mjkagnes123** [comment]
I looked that Ts increment from GSI (x0048) assimilated only each MW observation type.The majority of the Ts increments generated by microwave sensors come from AMSUA-A and ATMS, with only a small contribution from MHS. (double checked and confirmed that no Ts increments from GMI, AMSR2, and SSMIS)

x0048_mhs_ts_inc
x0048_atms_ts_inc
x0048_amsua_ts_inc
me from AMSUA-A and ATMS, with only a small contribution from MHS.

Here is the Ts increment from x0050 modified to assimilate only MW radiance observations.
x0050_allmw_ts_inc

**Comment by mjkagnes123** [comment]
My understanding is that increasing the values in 'obserr_demisf' in this PR will penalize the observations more, particularly when the first-guess Tb sensitivity to emissivity in CRTM is significant. I am totally okay with this, and I think that's how it should have been even in GSI. However, what still puzzles me is why the Ts increment in the original JEDI run (shown in Ricardo's first plot) was that high, and what could cause that huge difference shown in the 1st plot.

**Comment by gmao-wgu** [comment]
This change will cause our Tier 1 and Tier 2 tests to fail unless we intentionally ignore them.

**Review by mjkagnes123 — APPROVED** [review]
My understanding is that increasing the values in 'obserr_demisf' in this PR will penalize the observations more, particularly when the first-guess Tb sensitivity to emissivity in CRTM is significant. I am totally okay with this, and I think that's how it should have been even in GSI.  (i.e. "Green" light for this review and this PR.).   

However, what still puzzles me is why the Ts increment in the original JEDI run (shown in Ricardo's first plot) was that high, and what could cause that huge difference shown in the 1st plot.

**Comment by gmao-yzhu** [comment]
I agree with both what Ming-Jeong and Wei said. On one hand, to make Ts increments comparable between GSI and JEDI, increasing obs error inflation would help to acheive that; on the other hand, it will make our UFO tests fail, and we haven't done any tests to verify the impact of doing such. You both mentioned one question -- why they are so different given that the same CRTM is used. Could you compare the background used in the CRTM Tb calculation?

**Comment by rtodling** [comment]
All - it's okay that you don't agree w/ my proposed changes. But I also don't think changing observations errors would be justifiable either - simply for the same reasons: JEDI should take the configuration of GSI. 

Now clearly, JEDI has a problem handling the emissivities. So, I need to put the work of figuring out why is it that JEDI handles emissivities so differently than GSI, on you.

I hope you can and will take the time to figure this out. I, for my part, will no longer look at this - but I will also not cycle w/ the values that we have since I will be wasting my time.

**Comment by rtodling** [comment]
> I looked that Ts increment from GSI (x0048) assimilated only each MW observation type.The majority of the Ts increments generated by microwave sensors come from AMSUA-A and ATMS, with only a small contribution from MHS. (double checked and confirmed that no Ts increments from GMI, AMSR2, and SSMIS)
> 
> x0048_mhs_ts_inc x0048_atms_ts_inc x0048_amsua_ts_inc me from AMSUA-A and ATMS, with only a small contribution from MHS.
> 
> Here is the Ts increment from x0050 modified to assimilate only MW radiance observations. x0050_allmw_ts_inc

@mjkagnes123 Perhaps it is not clear to you: but all that you are showing here, I have already produce on my own. I exactly what the Ts increment looks like for every single combination of the radiance observing system. Thank you though.

**Comment by rtodling** [comment]
> Are the large differences in the Ts and emissivity sensitivity between GSI and JEDI due to background interpolation differences(GeoVals) or potential bugs in the CRTM interface in JEDI?

@gmao-wgu why would the differences you refer to produce a factor of 5 or 10 difference in increments when the difference in temperature is of a few percents? Also, why the differences you refer to would produce different magnitude of Tskin increments for different instruments (MW vs IR)?  

These are indeed rhetorical question, I am sorry to say, I don't think B has anything to do w/ this. But if you can prove me wrong ... all good.

**Comment by gmao-wgu** [comment]
@rtodling  I was confused here. Looking back, I don’t recall seeing any plots directly showing significant differences in Ts and surface emissivity sensitivity, which are used to inflate observation errors in both MW and IR, between GSI and JEDI. Perhaps I missed something.

**Comment by gmao-wgu** [comment]
Secondly, when you increase those coefficients by a factor of 5, it does not necessary translate to the observation errors being 5 times larger.

**Comment by gmao-wgu** [comment]
We know that the background errors used in JEDI are larger compared to those in GSI. If you reduce the background errors slightly, you might achieve similar results to those obtained with the inflated coefficients by a factor of 5.

**Comment by rtodling** [comment]
> We know that the background errors used in JEDI are larger compared to those in GSI. If you reduce the background errors slightly, you might achieve similar results to those obtained with the inflated coefficients by a factor of 5."

The same way you guys are not willing to make the changes here, I am not wiling to make the change in the background errors - the whole reason I introduced GSIBEC w/ the help of Dan was to avoid tuning the background errors.  Sorry.

**Comment by gmao-wgu** [comment]
@rtodling It is entirely your call. I support whatever decision you make to make it work.

**Review by gmao-wgu — APPROVED** [review]

**Comment by gmao-yzhu** [comment]
I see both Wei and Min-Jeong approved this PR. I’m fine with this, which might be the easiest way to adjust, we can take a closer look later once we have the system ready. We will need to remember that after this change we should not expect UFO tests for ATMS and AMSUA to pass.

From: Wei Gu ***@***.***>
Date: Monday, December 16, 2024 at 7:52 PM
To: GEOS-ESM/swell ***@***.***>
Cc: Zhu, Yanqiu (GSFC-6101) ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [GEOS-ESM/swell] MW: Revised coeffs scalling emissivity term in surf Jacobian (PR #474)
CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



@gmao-wgu approved this pull request.

**Comment by rtodling** [comment]
Ok, as we talked about in the meeting this AM, I looked at the UFO ... I am looking at channel 5 from ATMS-N20. And this is what I am finding (an example), the swell code/settings in develop produce the following scatter for Final Obs Errors JEDI vs GSI:

orig

The following is unfortunately what I get with the proposed changes in this PR:

prop

The above seem clearly to be against the change in ATMS (I see the same in the ATMS on NPP).

But oddly enough, I don't see this in AMSUA-N19 channel 5 and 4, but I do see a little off-centered scatter for AMSUA-N18, chan 4.

So, given these ... I am going to close this issue ... and look for a solution to the increment results elsewhere.

**Comment by gmao-yzhu** [comment]
Ricardo, Thanks very much for doing tests.


From: rtodling ***@***.***>
Date: Wednesday, December 18, 2024 at 1:33 PM
To: GEOS-ESM/swell ***@***.***>
Cc: Zhu, Yanqiu (GSFC-6101) ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [GEOS-ESM/swell] MW: Revised coeffs scalling emissivity term in surf Jacobian (PR #474)
CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



Ok, as we talked about in the meeting this AM, I looked at the UFO ... I am looking at channel 5 from ATMS-N20. And this is what I am finding (an example), the swell code/settings in develop produce the following scatter for Final Obs Errors JEDI vs GSI:
orig.png (view on web)<https://github.com/user-attachments/assets/b951ba50-f31f-4201-a137-e66e5ac0b8f7>

The following is unfortunately what I get with the proposed changes in this PR:
prop.png (view on web)<https://github.com/user-attachments/assets/c3033172-af0b-4b1b-bef1-d3f9a5425d26>

The above seem clearly to be against the change in ATMS (I see the same in the ATMS on NPP).

But oddly enough, I don't see this in AMSUA-N19 channel 5 and 4, but I do see a little off-centered scatter for AMSUA-N18, chan 4.

So, given these ... I am going to close this issue ... and look for a solution to the increment results elsewhere.

**Pull request closed without merging**
