### PR TITLE
Updates to eva API

### PR DESCRIPTION
**Pull request by danholdaway**
## Description

Recent changes to the eva API means changes to where swell accesses eva.

## Dependencies

- [ ] waiting on https://github.com/danholdaway/eva/pull/14

### CODE REVIEW

**Review by jardizzo — APPROVED** [review]
Looks like create_and_run() is now part of object instantiation? The only comment that I have is that "Run the diagnostic application" is obfuscated by the instantiation versus the invocation of a method of the object that has an explicit name (e.g. eva.run_diag()). I may be misinterpreting the code however.

**Comment by danholdaway** [comment]
> Looks like create_and_run() is now part of object instantiation? The only comment that I have is that "Run the diagnostic application" is obfuscated by the instantiation versus the invocation of a method of the object that has an explicit name (e.g. eva.run_diag()). I may be misinterpreting the code however.

@jardizzo I'm not sure I understand your comment. Could you elaborate? In this case the thing provided by eva is just a method rather than an object. The method will create an object but it's not accessible to swell.

**Comment by jardizzo** [comment]
OK, I understand now. The eva() method instantiates an object generated by a factory that is a function of the dictionary passed in. So my comment is simply that eva() does not denote an action. Perhaps eva_run()? Feel free to ignore.

**Comment by danholdaway** [comment]
That was already decided in an eva code sprint development last week and merged into develop so we have to take it at face value.

**Pull request merged**
