### PR TITLE
Oct 2024 Variable Change Sprint

### PR DESCRIPTION
**Pull request by rtodling**
## Description

**All this is using JEDI from 19Nov2024. So this is following JEDI build update to November 19th**

Working to address changes from October 2024 Variable Change Sprint. 

- Geoval names were updated and relevant R2D2 files and folders were updated to handle this change. Now new folders are named v3 and set as the default
- Erased some of the overwrites in Tier 1 tests to prevent confusion
- `fields_metadata.yaml` changed for SOCA
- Sea-ice variable names changed. 
 
These now work for all of the atmospheric obs systems:

However, in the SSMI case, I am seeing the Jo got down to negative numbers ... this means something is odd somewhere - bias correction, or something. I am not sure whether this was the case in the original code (before all these changes) ... I am currently checking on that.

# SOCA notes:

There are major changes in terms of what internal variable names SOCA would be using and hence the configuration yamls needed to be updated. In terms of MOM6 outputs or obs files, there are no changes. See more details in https://github.com/JCSDA-internal/soca/pull/1082. For instance instead of `tocn` we set `sea_water_potential_temperature`.

It also conforms with https://github.com/JCSDA-internal/soca/pull/1085, `BkgErrGODAS` is moved out to the generic block. Most of the default balance values were what we have been using but there is an additional `OceanSmoother` that we should be careful about.

### CODE REVIEW

**Comment by rtodling** [comment]
General comment about what will be required in terms of getting the UFO test working -- we'll need to go over the variable name changes seen in the yaml; look for the geovals that changed names, and rename those variables in the geoval files of the corresponding instruments. This is a relatively simple task ... I might work on that later today.

**Comment by rtodling** [comment]
So I am confirming that the problem I see w/ SSMI/S is already in develop:

Quadratic cost function: JoJc( 0) = 2904.536994156287
Quadratic cost function: JoJc( 1) = 1761.685897988107
Quadratic cost function: JoJc( 2) = 41.58146053894939
Quadratic cost function: JoJc( 3) = -2188.836274347395
Quadratic cost function: JoJc( 4) = -4574.266068595534
Quadratic cost function: JoJc( 5) = -7173.171878308596
Quadratic cost function: JoJc( 6) = -8398.747569179868
Quadratic cost function: JoJc( 7) = -9260.910107256032
Quadratic cost function: JoJc( 8) = -9691.212019756096
Quadratic cost function: JoJc( 9) = -9915.784237898803
Quadratic cost function: JoJc(10) = -10072.29704553444

So the changes introduced in this PR are not related to this issue. I will open an issue regarding this.

**Comment by rtodling** [comment]
At this stage, I say that all work to merge w/ Sprint (19Nov2024 version of JEDI) has been done for VAR.

Work needs to be done for:

SOCA and HOFX/UFO

**Comment by Dooruk** [comment]
Can you share the November build you are using so I can also test with it?

**Comment by rtodling** [comment]
I have now a script that converts the variables in the geovals files according to the Sprint changes. I have triggered the UFO testing for all  obs types ... except for aircraft and gps which seems to give me an unrelated error - all seems to work. I think I might be able to figure out the gps one ... the aircraft relates to a bias correction issue - not clear what's going on.

The only thing I have not tested - cause I don't know how - is SOCA. But for atmosphere I now believe to have all needed changes. Somebody w/ super-powers will need to run the script I created over the geovals files stored in the original place.

**Comment by rtodling** [comment]
**(Doruk) This is done now:**

~The following following should be done to allow the UFO tests to working for versions of JEDI pass the Oct 2024 Code Sprint:~

~cp -r /gpfsm/dnb33/rtodling/R2D2DataStore/Shared/ncdiag/ob/x0048v3-geovals  /discover/nobackup/projects/gmao/advda/R2D2DataStore/Shared/ncdiag/ob/~

**Comment by rtodling** [comment]
@Dooruk why do we need all these requests for review?

**Comment by Dooruk** [comment]
> @Dooruk why do we need all these requests for review?

It's more of a heads up for everybody but we can go ahead and merge it

**Review by Dooruk — APPROVED** [review]
`3dvar` still fails on the runners but not during local tests, but I don't want to hold this back. I asked SI-team and @mranst 's help on this.

**Comment by gmao-msienkie** [comment]
I ran swell-convert_ncdiags-suite and the ncdiag file for aircraft that was generated still has the 'windUpward' name in the metadata and not the new 'instantaneousAltitudeRate'.  I guess that converter needs an update as well.

**Comment by Dooruk** [comment]
> I ran swell-convert_ncdiags-suite and the ncdiag file for aircraft that was generated still has the 'windUpward' name in the metadata and not the new 'instantaneousAltitudeRate'. I guess that converter needs an update as well.

Sorry, SLES12 build wasn't updated to 11/19 but it is now 👍

**Pull request merged**
