### PR TITLE
Remove passive_bc option

### PR DESCRIPTION
**Pull request by danholdaway**
## Description

Turn off everywhere we have 

```yaml
use passive_bc: true
```
 Either commented or not. The deafult is false so removing sets it to false. This will probably change counts so @gmao-jjin3 @gmao-wgu are we OK with this in principle before we start testing it all out?

### CODE REVIEW

**Review by gmao-jjin3 — APPROVED** [review]

**Comment by gmao-jjin3** [comment]
> Either commented or not. The deafult is false so removing sets it to false. This will probably change counts so @gmao-jjin3 @gmao-wgu are we OK with this in principle before we start testing it all out?

I don't think it changes counts to remove it.   Counts were calculated without this passive BC configuration which is a flawed design because it simply turns on all these passive channels.

**Comment by gmao-yzhu** [comment]
I talked this with Ben Ruston last week, he took notes and will check with people in JCSDA. But this won't affect what we are doing here at this moment.

**Comment by gmao-wgu** [comment]
I observed use passive_bc also be used in the inter-channel consistency check for MW, it will not change the count of active channels, so it should be still set as .true. @

**Comment by danholdaway** [comment]
Thanks @gmao-wgu. I've updated the PR. The only thing really happening now is to turn it off for ATMS in the use flag filter.

**Comment by gmao-jjin3** [comment]
@gmao-wgu is right about which one should be "true".  The benchmark values came from my tests in which both were true, so they should be changed.

**Comment by danholdaway** [comment]
@gmao-jjin3 @gmao-wgu these changes require a change in count for ATMS. Are we OK with this?

**Comment by gmao-jjin3** [comment]
@danholdaway I am OK with that.  I can get new counts if you don't have them already.

**Comment by gmao-jjin3** [comment]
@danholdaway  See the numbers in https://github.com/GEOS-ESM/swell/pull/249

**Comment by danholdaway** [comment]
> @danholdaway See the numbers in #249

Those are the same counts we have here so I'll go ahead and merge. Thank you.

**Pull request merged**
